apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: simple-app-hpa
spec:
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - external:
        metricName: loadbalancing.googleapis.com|https|request_count
        targetAverageValue: "1"
      type: External
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: simple-app-deployment
