apiVersion: v1
kind: Service
metadata:
  name: simple-app
spec:
  ports:
    - name: "8080"
      nodePort: 32222
      port: 8080
      targetPort: 11130
  type: NodePort
  selector:
    app: simple-app