apiVersion: v1
kind: Service
metadata:
  name: simple-app
spec:
  type: LoadBalancer
  selector:
    app: simple-app
  ports:
    - port: 8080
      targetPort: 11130

# !!! Kubernetes service to handle request for our app.
# It delivers requests to deployment's port number 11130.